title: Zhiqiang Zang

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: _sass

## Override the theme used by github-pages with empty
theme:

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - vendor
  - .gitignore
  - .gitattribute
  - Gemfile
  - Gemfile.lock
  - README.md
  - TODO.md

## Defaults set by GitHub but we can change
# github: [metadata]
# encoding: UTF-8
# kramdown:
#   input: GFM
#   hard_wrap: false
# future: true
# jailed: false
# theme: jekyll-theme-primer
# gfm_quirks: paragraph_end

## Configuration settings we cannot change, overrided by GitHub when
## we push there
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge

## Default plugins are enabled by default and cannot be disabled
# - jekyll-coffeescript
# - jekyll-gist
# - jekyll-github-metadata
# - jekyll-paginate
# - jekyll-relative-links
# - jekyll-optional-front-matter
# - jekyll-readme-index
# - jekyll-default-layout
# - jekyll-titles-from-headings

## Optional plugins
# - jekyll-feed
# - jekyll-redirect-from
# - jekyll-seo-tag
# - jekyll-sitemap
# - jekyll-avatar
# - jemoji
# - jekyll-mentions
# - jekyll-include-cache
